name = "SignedDistanceFunctions"
uuid = "bf0eba9c-ecd3-4da3-b948-0885808c17e9"
authors = ["Cédric Belmant"]
version = "0.1.0"

[deps]
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[compat]
Meshes = "0.16"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
